#ifndef LIB842_TEST_DATA_H
#define LIB842_TEST_DATA_H

#include <stdint.h>
#include <stddef.h>

// Pair of (uncompressed data, compressed data) to be used as a source for tests
struct test842_pattern {
    // Uncompressed data
    const uint8_t *uncompressed;
    size_t uncompressed_len;

    // Compressed data (as generated by the reference implementation, i.e. the
    // actual hardware accelerator or the Linux kernel software fallback)
    const uint8_t *ref_compressed;
    size_t ref_compressed_len;
};

const struct test842_pattern *test842_get_pattern_by_name(const char *name);

#endif
